### ISSUE TITLE
It's ..

### ISSUE THREAD

**Issue by chicojor** [anspress/anspress#258]
Not working as a home page ... if u set it as a static page it will show but when you clicking on any question it will give you a (page not found )

**Comment by chicojor** [comment]
if you created a latest questions widget that will be nice as an additional choice ..

**Comment by rahularyan** [comment]
Okey I will.
Give this a try: do not uses base page as home page, instead set other page as as static home page and use `[anspress]` shortcode. let us know

**Comment by chicojor** [comment]
Yes I did , but still the same result

**Comment by rahularyan** [comment]
I will check and fix it.

**Comment by rahularyan** [comment]
Issue solved
