### ISSUE TITLE
Specify category in main anspress shortcode

### ISSUE THREAD

**Issue by AleCaste** [anspress/anspress#260]
Would it be possible to specify a category as an attribute for the main [anspress] shortcode so that the plugin only shows the questions within that category?
Likewise the search functionality should also support a category parameter so that the questions returned would belong to the specified category.

We would like to show questions & answers on different pages of our site, and those questions should refer to different subjects (categories). Showing ALL questions for ALL categories is not always ideal.

What do you think?

**Comment by rahularyan** [comment]
Will think about it today, and let you know.

**Comment by AleCaste** [comment]
Even better... maybe one of the arguments could be the query params like in SabaiDiscuss:
http://sabaidiscuss.com/documentation/shortcode/
I think is a good idea because it gives you all the flexibility.

Also, have a look at this. If I go to the page:
http://demo.sabaidiscuss.com/questions?sort=newest&keywords=&category=77
I get the questions for that category, and the search box is prepared to give me results within that category only. Neat.

**Comment by rahularyan** [comment]
Yep, I think his will be helpful. will add it.

Regards,
Rahul Aryan
www.rahularyan.com


Date: Sat, 7 Mar 2015 20:14:14 -0800

**Comment by devinbalkind** [comment]
I very much look forward to having the ability to use shortcodes to display all questions associated with a  category.

Great plugin.  Thanks!

**Comment by rahularyan** [comment]
@devinbalkind here is what you are lookingfor:
[anspress categories="3,4,5"]
