### ISSUE TITLE
Overlapping permissions

### ISSUE THREAD

**Issue by chic0jordan** [anspress/anspress#263]
<img src="http://faclon.byethost5.com/ask/wp-content/uploads/2015/03/Ashampoo_Snap_2015.03.16_01h26m29s_002_.jpg" alt="ask box" />

if you select this choices .. users can send questions and answers without login

<img src="http://faclon.byethost5.com/ask/wp-content/uploads/2015/03/Ashampoo_Snap_2015.03.16_01h39m36s_003_.jpg" alt="ask box" />

how we can make user without login just question without be able to answer and  the admin he can answer only ..

**Comment by rahularyan** [comment]
I will add this option
