### ISSUE TITLE
Base page breadcrumb item missing

### ISSUE THREAD

**Issue by TheZoker** [anspress/anspress#270]
When you are on the question details page, the base page item is missing in the breadcrumb.

Eg.
page: www.site.com (Breadcrumb "Home")
anspress: www.site.com/anspress (Breadcrumb "Home -> Anspress")
question: www.site.com/anspress/question/123 (Breadcrumb "Home" -> "Question")

The last breadcrumb should be "Home" -> "Anspress" -> "Question"

**Comment by rahularyan** [comment]
which plugin you were using ?

**Comment by TheZoker** [comment]
Yoast SEO:
https://wordpress.org/plugins/wordpress-seo/

**Comment by gubi** [comment]
This problem still continuing exists for me :(

**Comment by rahularyan** [comment]
yost breadcrumb or AnsPress breadcrumb ?

**Comment by bdchauvette** [comment]
Hi @rahularyan! Great plugin!

Sorry to resurrect this issue, but I'm unfortunately having the same problem.

I'm also having the problem of yoast breadcrumbs (& Breadcrumb NavXT) resetting the page title.

If I enable the `Show question titles in single page`, the normal page title is wrong, but the added page title is correct (see attached image for example of all three).

---

Less related, but I also can't get the AnsPress breadcrumb widget to work, as it gives the following error when placed in the `AP Before` slot:

```
Fatal error: Call to undefined function is_question_tag() in /path/to/wordpress/wp-content/plugins/anspress-question-answer/includes/theme.php on line 821
```

## Versions

- **AnsPress** - Latest Github commit (2.4rc / 9a321de6ea)
- **Yoast SEO** - 2.3.4
- **Colormag Theme** - 1.0.8

## Things I've tried

None of the following have worked. The base page name is always displayed as the page title.

- Hooking into `the_title`
- Add the breadcrumb code directly into `page.php`
- Replacing Yoast breadcrumbs with `Breadcrumb NavXT` (v5.2.2)

## Current breadcrumb code
```php
/*
 * functions.php in child theme
 */
add_action('colormag_before_post_content', 'add_breadcrumbs_to_single');

function add_breadcrumbs_to_single() {
  if (function_exists('yoast_breadcrumb')) {
    yoast_breadcrumb('<p id="breadcrumbs">','</p>');
  }
}
```

```php
/*
 * page.php from parent theme
 */
<article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
	<?php do_action( 'colormag_before_post_content' ); ?>

	<header class="entry-header">
		<h1 class="entry-title">
			<?php the_title(); ?>
		</h1>
	</header>

. . .
```


## Screenshot

![screenshot](https://cloud.githubusercontent.com/assets/1448597/9815399/16a4bfd2-5896-11e5-919c-07d972b522bc.png)

**Comment by rahularyan** [comment]
I will check the issue.
