### ISSUE TITLE
Add support for slack

### ISSUE THREAD

**Issue by TheZoker** [anspress/anspress#271]
Would be awesome, if you could support for slack (very easy):
https://api.slack.com/incoming-webhooks

**Comment by rahularyan** [comment]
is this a totally free push service ?

**Comment by TheZoker** [comment]
Yea totaly free team communication and push service :)

**Comment by rahularyan** [comment]
Its cool then, I was searching for a push service this morning

**Comment by TheZoker** [comment]
Its an awesome application with many integrations:
https://slack.com/is/
https://slack.com/integrations

**Comment by TheZoker** [comment]
Any news about that?

**Comment by rahularyan** [comment]
No not yet.

Before slack I will add Github and Asana integration

Regards,
Rahul Aryan
www.rahularyan.com


Date: Mon, 6 Apr 2015 04:46:14 -0700
