### ISSUE TITLE
Some bugs/feature request

### ISSUE THREAD

**Issue by TheZoker** [anspress/anspress#279]
Bugs:
- "Status" and "..." link are not working (nothing happens)
- Inserting url only works when "title" is inserted. Normaly it should take the url itself, if no title is defined. Also #161 does not work
- base page is missing in url
- Icon is not aligned right

![img_2015 04 27_19h46m31s_004_](https://cloud.githubusercontent.com/assets/1368405/7353734/2696aeb4-ed16-11e4-8063-0aaa3483cad5.png)

- ```Fatal error: Call to a member function have_posts() on a non-object in /wp-content/plugins/anspress-question-answer/includes/question-loop.php on line 166```

Features:
- Highlight selected answers 
- Move question activity to the total top, so its clear that the activity belongs also to answers/comments etc
- Add breadcrumb support

BTW: The new design is awesome :D

**Comment by rahularyan** [comment]
Do you have latest commit ? 
Let me check.

And please use our site for reporting issues. After publishing anspress.io I will completly disable issue tracker in github, we will use our own issue tracker.

**Comment by TheZoker** [comment]
Yes I`m using the absolute latest commit.

**Comment by rahularyan** [comment]
dropdown issue has been solved. Let me know.

**Comment by TheZoker** [comment]
Yes fixed :)
Only this issue related to dropdowns:
![img_2015 04 28_15h05m24s_010_](https://cloud.githubusercontent.com/assets/1368405/7370126/134b83b4-edb8-11e4-960a-72d07b836562.png)

Both can be opened at the same time...

**Comment by rahularyan** [comment]
what do you mean by this ? please describe with screesnhot.
Inserting url only works when "title" is inserted. Normaly it should take the url itself, if no title is defined. Also #161 does not work

**Comment by TheZoker** [comment]
![img_2015 04 28_15h25m00s_011_](https://cloud.githubusercontent.com/assets/1368405/7370556/340ec996-edbb-11e4-9dbd-ccff3b3147e2.png)
![img_2015 04 28_15h26m10s_012_](https://cloud.githubusercontent.com/assets/1368405/7370557/3410f8b0-edbb-11e4-851e-0d20248527d2.png)

**Comment by rahularyan** [comment]
When u see this error?
Fatal error: Call to a member function have_posts() on a non-object in /wp-content/plugins/anspress-question-answer/includes/question-loop.php on line 166

**Comment by TheZoker** [comment]
I see this error on the Anspress Question widget...
