### ISSUE TITLE
Authorize anonymous voting & disable registration or just identify yourself with a username and possibly a PIN code

### ISSUE THREAD

**Issue by HLFH** [anspress/anspress#28]
Hi,

I know it's maybe a bad idea.
I would like to:
-Authorize anonymous voting + submitting and disable registration 
-or just identify yourself with a username and possibly a PIN code

**Comment by kreion** [comment]
Hello guys, is there a possibility that anonymous voting will be added in future? Or any ideas about workaround to make voting also possible for anonymous users?

**Comment by JonathanM2** [comment]
Yeh. It may be get added in future. This is in our feature request list.

We cannot say the exact time of implementation at the moment.

But it will be very easy to add, you just have to update question meta.

---- Sent from outlook app for Android ----

--- Original Message ---
