### ISSUE TITLE
[Improvement] Make theming like woocommerce

### ISSUE THREAD

**Issue by jandosul** [anspress/anspress#282]
1. Make it possible to override templates via regular single-question.php archive-question.php templates files. It gives ability change templates without touching/copying plugin theme dir into theme and diving into plugin hooks. 
2. Moving from meta keys to custom taxonomies for question groups like unsolved, unanswered etc. It will be more elegant way, imho.
Thanks for great plugin!

**Comment by rahularyan** [comment]
1. Beta 2.0 was like that, but many people thought AnsPress is broken so I reverted.
2. Will think about it :)
