### ISSUE TITLE
Integrate it with EDD?

### ISSUE THREAD

**Issue by gudh** [anspress/anspress#295]
Hi, thanks for building this amazing Q&A plugin!

One quick question: Have you think about integrating it with [EasyDigitalDownloads](https://easydigitaldownloads.com/)? 

That is if the user is a buyer, you can show a "buyer" tag right below their profile, and the administrators can click to know what exactly they bought.

I will probably buy one if the price is reasonable :)

Again, thanks for the plugin!

**Comment by rahularyan** [comment]
I also use EDD, and this feature request is already in my task list. After I major task completes then I will work on this. Cheers!

**Comment by gudh** [comment]
@rahularyan cool!
