### ISSUE TITLE
Localization problem

### ISSUE THREAD

**Issue by gable44** [anspress/anspress#299]
The "Toggle fullscreen" phrase can not be translated by po edit

**Comment by rahularyan** [comment]
will check

**Comment by gable44** [comment]
Also the phrase: *user* updated 10 minutes ago
Can only be translated to this: Username frissítette 10 perc ezelőtt
But Hungarinan language uses suffixes like "perccel" elezőtt.
Could you expand the pot file to translate the minute(s), hour(s), year(s) and the other phrases?

**Comment by rahularyan** [comment]
@gable44 minute(s), hour(s), year(s) are returned from wordpress, so it cannot be translated from AnsPress .pot.
Please attach a screenshot pointing to all non-translating strings. I will check the all and fix if any issue.
Cheers.

**Comment by gable44** [comment]
I know it used by wordpress but in their context the translation is good but as I sad Hungarian using suffixes. That is why some plugins using these kind of phrases from their translation.
(I don't think I should attach sreens because that method will solve the problem)

**Comment by BRoz** [comment]
Category from ask page is not translatable in poedit. Also select a topic to..
all categories in the category page, or in the base page.
ago. is not translated. 
tooggle fullscreen is not translated.
Loading text when passing over a photo and appear the box for the profile too.

**Comment by JonathanM2** [comment]
Will be checked and fixed soon. Please post it in anspress.io (if you can) instead of github.

---- Sent from outlook app for Android ----

--- Original Message ---

**Comment by rahularyan** [comment]
@BRoz 
Category from ask page is not translatable in poedit. Also select a topic to..
-- will fix this today

**Comment by BRoz** [comment]
Thanks @JonathanM2 i will do it on anspress.io next time. I am finishing italian translation of the plugin and i will tell you every missing string.
Next there is a bug with the hover profile card, i want to understand if it is the fault of the theme i am using. I will let you know asap

**Comment by BRoz** [comment]
Thanks @JonathanM2 i will do it on anspress.io next time. I am finishing italian translation of the plugin and i will tell you every missing string.
Next there is a bug with the hover profile card, i want to understand if it is the fault of the theme i am using. I will let you know asap
