### ISSUE TITLE
I get blank page on my template

### ISSUE THREAD

**Issue by tsalexey544** [anspress/anspress#300]
I get blank page on my template. I didnt do any hardcore modifications. Just standard template, Aanspress works fine on other templates. What could be the problem? Are there any required files?

**Comment by rahularyan** [comment]
Can you post PHP error log ? and please post it here: http://anspress.io/questions/
Cheers

**Comment by tsalexey544** [comment]
That is the problem. No errors. Just blank. It show only the header and footer....
http://japanpapa.ru/questions 

What could be the problem?

**Comment by rahularyan** [comment]
please check your PHP error log and post the error here.

**Comment by tsalexey544** [comment]
Got the logs. Here it is - http://anspress.io/questions/question/i-get-blank-page-on-my-template/

**Comment by rahularyan** [comment]
ah sorry your question has been deleted by mistake.

there are 3 fatal error in your log, you must fix them first:

``[Tue Jun 30 18:25:29 2015] [error] [client 95.163.210.177] PHP Fatal error: Call to undefined function twentyfourteen_post_thumbnail() in /var/www/japanpaparu/data/www/japanpapa.ru/wp-content/themes/jpapa/content.php on line 14``

``[Tue Jun 30 18:25:32 2015] [error] [client 95.163.210.177] PHP Fatal error: Call to undefined function twentyfourteen_post_thumbnail() in /var/www/japanpaparu/data/www/japanpapa.ru/wp-content/themes/jpapa/content.php on line 14``

``[Tue Jun 30 18:35:25 2015] [error] [client 178.216.74.135] PHP Fatal error: Call to undefined function ap_get_page_template() in /var/www/japanpaparu/data/www/japanpapa.ru/wp-content/themes/jpapa/index.php on line 3``

**Comment by tsalexey544** [comment]
fixed) still blank....

**Comment by JonathanM2** [comment]
As this issue are coming from your theme, so u should ask your theme developer.
Even though if you can connect with team viewer, tomorrow ? I will try to help.
Cheers

**Comment by tsalexey544** [comment]
Yes that would be great) Thank you

**Comment by tsalexey544** [comment]
Finaly got it. I was missing content-page.php
