### ISSUE TITLE
Non-existant questions return 200 OK HTTP status

### ISSUE THREAD

**Issue by CybMeta** [anspress/anspress#301]
When you visit a non-existant question you can see a 404 error message in the page but 404 error is not triggered. You can check that the HTTP status header is 200 OK. That is very bad for SEO and it is not the correct HTTP status code for non-existent URL.

I've been digging into anspress code and I've found the the problem may be in `AnsPress_Common_Pages::question_page()` method. I have not time currently to investigate a possible solution, I hope to have time later this moth. By the moment I suggest to try [`status_header()` function](https://codex.wordpress.org/Function_Reference/status_header) and [WP_Query::set_404()](https://developer.wordpress.org/reference/classes/wp_query/set_404/) method for main query.

**Comment by rahularyan** [comment]
I confirm the bug. Kindly add it to anspress.io/questions/ask with in bug category.
Our roadmap is built based on bug category.
Thanks for reporting.

**Comment by rahularyan** [comment]
Issue solved
