### ISSUE TITLE
when viewing reputation page of another user into the buddypress userpage, we actually see our own reputation history

### ISSUE THREAD

**Issue by Krl4** [anspress/anspress#322]
When you enter the profile page of another user in buddypress and select reputation, You actually see your own reputation story… The total reputation on the top of the page beneath the username is actually ok, it only affects the reputation history: you always see your own reputation story whatever user page you're visiting.

![sin titulo-2](https://cloud.githubusercontent.com/assets/14329353/10461747/38e39d12-71db-11e5-9a2a-0019ab9c3bc5.jpg)
![sin titulo-3](https://cloud.githubusercontent.com/assets/14329353/10461748/38e8771a-71db-11e5-9064-4ec3ab469c20.jpg)

**Comment by rahularyan** [comment]
I will check.

**Comment by Krl4** [comment]
I noticed that it didn't work if the buddypress user page is not at the same level of the anspress base page. I mean, it only works if the anspress base page and the buddypress user page have both the same parent. If you create a page named buddypress and a sub-page below it named users, the anspressbase page need to be below the buddypress's page in order to the reputation page to work fine.
