### ISSUE TITLE
fatal Error

### ISSUE THREAD

**Issue by alexlii1971** [anspress/anspress#448]
fatal error upon activation when I tried to activate the version from: https://wordpress.org/plugins/anspress-question-answer/

http://prntscr.com/jabml9

Warning: require_once(/var/www/mysite.com/htdocs/wp-content/plugins/anspress-master/addons/reputation/reputation.php): failed to open stream: 
No such file or directory in /var/www/mysite.com/htdocs/wp-content/plugins/anspress-question-answer/includes/functions.php on line 1807

Alex

**Comment by rahularyan** [comment]
Hi Alex,

Please redownload. Those are core file present in repo. From whete you have downloaded?
________________________________

**Comment by alexlii1971** [comment]
I download it from wordpress backend plugin download:

http://prntscr.com/jac22v

Alex

**Comment by rahularyan** [comment]
Hello

**Comment by alexlii1971** [comment]
I note you fix it, should I tried it again?

Alex

**Comment by rahularyan** [comment]
Yes sure

Sent from Outlook for Android

________________________________
