### ISSUE TITLE
%d Answer translation

### ISSUE THREAD

**Issue by alexlii1971** [anspress/anspress#449]
Whatever I use the plugin of Local translate  or POedit

http://prntscr.com/janwk6
I can not make the translation works here.

in Chinese, there is no difference between single and Plural 
https://wordpress.org/support/topic/missed-form/

is this" 1 Answer and % answer" to show the number under Question? I mean here in this Screenshot:http://prntscr.com/jao0iu

If Yes, How should I make it ignore single or Plural? should edit Mo file but not Po file?

Alex

**Comment by rahularyan** [comment]
Please do not posts questions here.
You should simply use `% answer` in singular field.
