### ISSUE TITLE
Version 4.9.5 with Captcha enabled throws JS console error, preventing further JS from executing

### ISSUE THREAD

**Issue by apavlinovic** [anspress/anspress#453]
## Current Behavior
If you enable reCaptcha addon on 4.9.5, the plugin renders a naive JS snippet (abridged version below):

```
jquery.on('ready', () => {
   Anspress.captcha = {}
})
```

This fails on Newspaper theme (and apparently on default TwentySeventeen), possibly other themes as well. Not sure why.

## Possible Solution
Monkey patch it.

```
jquery.on('ready', () => {
   window.Anspress = Anspress || {};
   window.Anspress.captcha = {}
})
```
or render the required property on root Anspress script renderer.

## Context (Environment)

This is a major issue as it literary stops further JS from executing.

**Comment by rahularyan** [comment]
Thank you
