### ISSUE TITLE
How about make AP_Subscription_Hooks class?

### ISSUE THREAD

**Issue by rpf5573** [anspress/anspress#458]
I saw this code in init() of hooks.php
// Subscriptions
			anspress()->add_action( 'ap_after_new_question', __CLASS__, 'question_subscription', 10, 2 );
			anspress()->add_action( 'ap_after_new_answer', __CLASS__, 'answer_subscription', 10, 2 );
			anspress()->add_action( 'ap_new_subscriber', __CLASS__, 'new_subscriber', 10, 4 );
			anspress()->add_action( 'ap_delete_subscribers', __CLASS__, 'delete_subscribers', 10, 2 );
			anspress()->add_action( 'ap_delete_subscriber', __CLASS__, 'delete_subscriber', 10, 3 );
			anspress()->add_action( 'before_delete_post', __CLASS__, 'delete_subscriptions' );
			anspress()->add_action( 'ap_publish_comment', __CLASS__, 'comment_subscription' );
			anspress()->add_action( 'deleted_comment', __CLASS__, 'delete_comment_subscriptions', 10, 2 );

I think it is more good to make AP_Subscription_Hooks class and then insert functions in it.
How about my idea?

**Comment by rahularyan** [comment]
Hello,
I was doing same in past versions. But to organize the hooks I moved all hooks in one file. This helps me to find hooks easily and also prevent duplicate hooks.

**Comment by rpf5573** [comment]
Thanks for your reply! 
I got it.
