### ISSUE TITLE
why 'terms' in 'wp_ap_qameta' is needed?

### ISSUE THREAD

**Issue by rpf5573** [anspress/anspress#478]
I don't know why 'terms' is needed.
Would you please explain the purpose of terms ?

Check please!

**Comment by rahularyan** [comment]
Hi,
Can you kindly give me the file and line number which you are referring to?

**Comment by rahularyan** [comment]
Now I got it. There is no use of that `terms` in `ap_qameta` table. It will be removed. Thanks for reporting.
