### ISSUE TITLE
Wrong username in comments

### ISSUE THREAD

**Issue by stirlingsohn** [anspress/anspress#507]
When someone leaves a comment on a question or answer it shows the username of the question or answers author instead of the commenters. The correct avatar is shown though.

![grafik](https://user-images.githubusercontent.com/8092755/47289611-d1502c00-d5fb-11e8-823a-5f1544a80349.png)

**Comment by rahularyan** [comment]
Seems like this may be related to a caching plugin. Which cache plugin you are using. Can you try once disabling those plugins?
