### ISSUE TITLE
can not Filtering Posts When Click Filter in the Dashboard

### ISSUE THREAD

**Issue by wakasann** [anspress/anspress#517]
plugin version: 4.1.5
WordPress 4.8.9

at wordpress beckend
1.  Anspress -> Questions page,the browser  url like `edit.php?post_type=question`,,question list is fine ✔️ 
2. When Click Questions page Filter Button,url like `edit.php?s&post_status=all&post_type=question&action=-1&m=0&category&paged=1&action2=-1` ,the Question list is only show `Questions` record ❌ 
3. I try remove the query url `s&`  string,url `edit.php?post_status=all&post_type=question&action=-1&m=0&category&paged=1&action2=-1`, question list is fine ✔️ 

other custom post type,wordpress default post type at filtering,not working fine

i try inactive anspress plugin,pages or posts filtering is working fine,active anspress again filtering not working fine

![ap2](https://user-images.githubusercontent.com/5716243/57348580-3418a780-7189-11e9-8221-2eea44ba8a8d.gif)

**Comment by wakasann** [comment]
i found file `includes/hooks.php`  line 62 have `anspress()->add_filter( 'posts_pre_query', 'AP_QA_Query_Hooks', 'modify_main_posts', 999999, 2 );`

i change the code,at wordpress admin questions list  will not run this method code to replace the search result

```
/**
	 * Modify main query.
	 *
	 * @param array  $posts  Array of post object.
	 * @param object $query Wp_Query object.
	 * @return void|array
	 * @since 4.1.0
	 */
	public static function modify_main_posts( $posts, $query ) {
		if ($query->is_main_query() && $query->is_search() && 'question' === get_query_var( 'post_type' ) ) {
			$query->found_posts   = 1;
			$query->max_num_pages = 1;
			$posts                = [ get_page( ap_opt( 'base_page' ) ) ];
		}

		return $posts;
	}
```

to

```
/**
	 * Modify main query.
	 *
	 * @param array  $posts  Array of post object.
	 * @param object $query Wp_Query object.
	 * @return void|array
	 * @since 4.1.0
	 */
	public static function modify_main_posts( $posts, $query ) {
		if (!is_admin() && $query->is_main_query() && $query->is_search() && 'question' === get_query_var( 'post_type' ) ) {
			$query->found_posts   = 1;
			$query->max_num_pages = 1;
			$posts                = [ get_page( ap_opt( 'base_page' ) ) ];
		}

		return $posts;
	}
```

**Comment by wakasann** [comment]
i think this issue seem a bug,i reopened

**Comment by wakasann** [comment]
i just comment `includes/hooks.php` at line 62 when anspress base page is created

```
anspress()->add_filter( 'posts_pre_query', 'AP_QA_Query_Hooks', 'modify_main_posts', 999999, 2 );
```

change to

```
//anspress()->add_filter( 'posts_pre_query', 'AP_QA_Query_Hooks', 'modify_main_posts', 999999, 2 );
```

**Comment by rahularyan** [comment]
Hello @wakasann 
Thanks for reporting and I apologize for late response. This will be merged.
