### ISSUE TITLE
Translation is not working for human time

### ISSUE THREAD

**Issue by annikovk** [anspress/anspress#519]
In the following file: 

./wp-content/plugins/anspress-question-answer/includes/functions.php

There is a typo on string 257: 
```
	if ( $time ) {
		if ( $show_full_date + $time > current_time( 'timestamp', true ) ) {
			return sprintf(
				/* translators: %s: human-readable time difference */
				_x( '%s ago', 'anspress-question-answer' ),
				human_time_diff( $time, current_time( 'timestamp', true ) )
			);
		}
		return date_i18n( $format, $time );
	}
```

_x is defined instead of double underscore: 

```_x( '%s ago', 'anspress-question-answer' ),```

That is the reason why changes in translate file do not apply to actual question meta. 
The correct syntax: 

```__( '%s ago', 'anspress-question-answer' ),```

**Comment by alexlii1971** [comment]
Hello,

There is another one that could not be translated as this screenshot:http://prntscr.com/ns7nl0

would you please let me know how to translate it?


Thanks

**Comment by nash-ye** [comment]
Thanks for reporting the issue.
I also faced this problem and uploaded a pull request.
I hope the author merges the solution soon.

**Comment by nash-ye** [comment]
@rahularyan Is the change included in the latest update of the plugin yet?

**Comment by rahularyan** [comment]
Hello @nash-ye 
No, it will be published this Sunday along with few other bug fixing.
Thanks
