### ISSUE TITLE
Use user_trailingslashit() in the links of questions, categories..etc

### ISSUE THREAD

**Issue by nash-ye** [anspress/anspress#529]
Hello,

If you can please review the issue of forcing a trailing slash on the plugin's generated links. By the use of user_trailingslashit() to decide whether a trailing slash should be added or not.

**Comment by rahularyan** [comment]
Hello @nash-ye 
I will check this Sunday.

**Comment by nash-ye** [comment]
Thank you so much.
Any updates?
Please, tell me if there is anything I can help you with.

**Comment by rahularyan** [comment]
Hello @nash-ye 
This is fixed in 4.1.18
