### ISSUE TITLE
Don't add automated post status when ap_current_user_ignore is set

### ISSUE THREAD

**Issue by nash-ye** [anspress/anspress#531]
Currently, this is a wrong behavior in Question_Query that adds `private_post`, `moderate`, `future` and `trash` even if the option `ap_current_user_ignore` is set to true.

**Comment by rahularyan** [comment]
Hello @nash-ye 
Thanks for reporting, we are looking into this.

**Comment by rahularyan** [comment]
Hello @nash-ye I was not able to merge your PR because of multiple unnecessary "new lines" . But your suggestion was added.
