### ISSUE TITLE
Cannot ask questions at anspress.io even when logged in

### ISSUE THREAD

**Issue by MountainX** [anspress/anspress#534]
Hello. Asking for a friend:

Trying to ask question at main AnsPress site: https://anspress.io/questions/ask/?category=200.

Click the "Submit Question" button, nothing happens. 

Below the "Submit Question" button, the message "Hello Visitor! You need to login before accessing this page" is shown. However, in the upper right it shows "logout" (which means the user is logged in. User can access their account section, confirming they are logged in.

After trying to submit the question, there is no confirmation. The user's account shows that they have not asked any questions yet. Looks like the question is not being submitted.

We are using Firefox (latest) in Linux.

**Comment by rahularyan** [comment]
Already answered, https://github.com/anspress/anspress/issues/535
Thanks
