### ISSUE TITLE
AnsPress.io new user registration broken?

### ISSUE THREAD

**Issue by MountainX** [anspress/anspress#535]
Attempting to registering at AnsPress site: https://anspress.io/

Click the "Login" button in upper right and nothing happens. (That's confusing.)

Instead, click "Ask Question" and now you get a login or register form at: https://anspress.io/questions/ask/. 

Fill out the registration and submit. There is a long delay. Seems slow. But eventually it says "Registration complete. Please check your e-mail." However, the email does not come (and it is not in spam). Repeat tests indicate this email never arrives.

However, we noticed that you can now do the reset password function, set a password and login successfully. **This is clearly not a user friendly login process.** Is this normal for AnsPress? Will it be the same on our own WP site with AnsPress or is this a quirk of anspress.io? We can't launch a new website and expect users to register with this process.

I tested in Firefox (latest) on Linux. My friend tested with Chrome on Windows.

**Comment by rahularyan** [comment]
Hello @MountainX 
Thanks for reporting. This was disabled for a reason and apologize for not having any kind of notification. This was resolved.
