### ISSUE TITLE
Question Activities Not Updating

### ISSUE THREAD

**Issue by MountainX** [anspress/anspress#536]
We installed a new WordPress site on Siteground (SG). Other than the two default SG plugins, AnsPress was the first plugin installed. It is currently the only plugin activated. This is our first time using AnsPress.

We have created several users, several questions and some answers.

What we have notice so far is:

- the questions/activity page is not updating as new questions are asked. It shows some activity, but most is missing, even after hours have elapsed.
- every tag shows "0 Questions" even though we have questions with those tag

Are these known issues? What is the solution?

**Comment by rahularyan** [comment]
Hello @MountainX 
I hope this is happening because of redis cache plugin. This plugin was enabled by default by many hosting providers. I will look into that.
