### ISSUE TITLE
Editor not displaying properly

### ISSUE THREAD

**Issue by MountainX** [anspress/anspress#537]
We installed a new WordPress site on Siteground (SG). Other than the two default SG plugins, AnsPress was the first plugin installed. It is currently the only plugin activated. This is our first time using AnsPress.

When answering a question, the editor buttons disappear as shown in the screenshot here: https://imgchest.com/p/pwl7l3o37x2

It may be related to this bug: https://anspress.io/resources/faq/tinymce-fails-to-load-when-using-autoptimize-plugin/

However, that bug is related to the Autoptimize plugin, and we do not have any other WP Plugins activated. Furthermore, in the present issue the buttons have functionality -- when clicked, they insert formatting codes into the editing area. Therefore, the issue is about display of the editor icons and I'm not sure if that is the same as the above issue.

**Comment by rahularyan** [comment]
Hello @MountainX 
This seems like a CSS issue. Can you please share link to your site?
