### ISSUE TITLE
Uncaught SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by cema93** [anspress/anspress#539]
I use WP 5.5 and have error
`Uncaught SyntaxError: Unexpected token u in JSON at position 0

    at JSON.parse ()

    at Function.n.parseJSON (jquery.js:4)

    at i.render (question.js:263)

    at i.renderItem (question.js:345)

    at question.js:351

    at Function.v.each.v.forEach (underscore.min.js:2)

    at i.each (backbone.min.js:2)

    at i.render (question.js:350)

    at HTMLDocument. (question.js:526)

    at i (jquery.js:2)`

for example, page with error https://povestka.by/question/16551/

**Comment by Nail757** [comment]
Hi, same problem. 'render' metod of anspress\assets\js\question.js causes jQuery crash while parsing undefined JSON, which leads to JS freeze on whole page:

render: function(){
			var attr = this.$el.find('[ap-vote]').attr('ap-vote'); //attr is undefined as there's no [ap-vote] found
// if(attr) // -- added this for fix
			this.model.set('vote', $.parseJSON(attr), {silent: true}); // this leads to fatal error
			return this;
		}

I've made a temporary fix for my project to make JS working by adding "if(attr)" in plugin's JS -- please consider adding this (or some more elegant solution) in future version.

You can see a fixed example on my project's page here:
https://azbyka.ru/vopros/kakovy-istochniki-ucheniya-cerkvi-o-satane-i-padenii-ego/
