### ISSUE TITLE
Ask a question Page Multi İnput error

### ISSUE THREAD

**Issue by baraci** [anspress/anspress#559]
On the Ask a Question page, the fields appear as three. Normally one should come from each area. I could not find it from settings.
Thanks
![Screenshot_1](https://user-images.githubusercontent.com/35598469/114668789-cfb5d980-9d09-11eb-9860-5c651ed8a4eb.jpg)

**Comment by cema93** [comment]
Does this issue occur with the default theme and other plugins disabled?

**Comment by rahularyan** [comment]
Hi @cema93,

I believe we can resolve this long-standing issue for now. Should anyone encounter a similar problem in the future, they can initiate a new discussion. Thank you for your assistance.

Furthermore, in the upcoming version, we're excited to announce support for the block editor and a revamped template system. Stay tuned for these enhancements!
