### ISSUE TITLE
Answer editor default placeholder image

### ISSUE THREAD

**Issue by mebishalnapit** [anspress/anspress#765]
When the user sets the **Answer editor?** to **Quick tags editor** then, the placeholder image is still same, i.e., the old/main TinyMCE editor placeholder image is still shown instead of Quick tags editor placeholder image.

### To Reproduce

1. Go to **AnsPress -> Settings**
2. Click on **Posts & Comments**
3. For the **Answer editor?** option, enable **Quick tags editor** if not already enabled
4. Go to any question page from the front end
5. Scroll down to the section from where the user can answer to the question and note down the placeholder image shown
7. Click on the answer editor section and note down how the editor tags display inside the editor

### Expected behavior

The placeholder image for the answer editor should match exactly about how the editor will be opened up after clicking on the answer editor section in order for the user to not get confusion on how it will be rendered later on.

### Screenshots

Enabling quick tags editor for Question and Answer:
![enabling-quick-tags-editor-for-question-answer](https://user-images.githubusercontent.com/7981492/232948789-a615599e-9afd-42d4-8d27-96ffd1e585ce.png)

Answer editor placeholder image before it's clicked:
![answer-editor-placeholder-image-before-clicking](https://user-images.githubusercontent.com/7981492/232949194-4de46025-5f55-4750-8804-ee91ba9c0fc9.png)

Answer editor after it's clicked:
![answer-editor-after-clicking](https://user-images.githubusercontent.com/7981492/232949280-c0b145cb-4fda-4865-acbc-2359773a5ba3.png)

### Desktop 

 - OS: Linux
 - Browser: Chrome, Firefox
 - Version: 4.3.0

**Comment by cema93** [comment]
Here is a screenshot from my website:
![image](https://github.com/anspress/anspress/assets/1865012/1b0d6a0c-a095-400a-b13f-b3595e9669e8)
