### ISSUE TITLE
Question about ap_after_new_question  action

### ISSUE THREAD

**Issue by cema93** [anspress/anspress#769]
Hi all!
I want to run custom function after new question was posted.
I found action ap_after_new_question but i dont know how to add my function. please share small example.

@mebishalnapit and @rahularyan please help :)
THX

**Comment by rahularyan** [comment]
Hi there!

To add your custom function to the `ap_after_new_question` action, you can use the `add_action()` function provided by WordPress. Here's an example of how to use it:
```
function my_custom_function() {
    // Add your custom code here
}

add_action( 'ap_after_new_question', 'my_custom_function' );
```

In this example, the `my_custom_function()` function is added to the `ap_after_new_question` action using the `add_action()` function. Whenever the ap_after_new_question action is triggered, WordPress will automatically call the `my_custom_function()` function.

You can replace `my_custom_function` with the name of your own custom function.

I hope that helps! Let me know if you have any further questions.

**Comment by cema93** [comment]
@rahularyan 
Hi.
i added your code to functions.php of my theme and it doesn't work
