### ISSUE TITLE
no save button in tools

### ISSUE THREAD

**Issue by DoctorGuidance** [anspress/anspress#904]
Hi,
There is no save button in settings-tools menu.

![image](https://github.com/anspress/anspress/assets/12963915/638b9fb5-8ace-4851-9aea-65596bf6fd4e)

![image](https://github.com/anspress/anspress/assets/12963915/ddc514d6-c8e0-4fd4-bf5f-e903f2ca11ba)

**Comment by rahularyan** [comment]
Hello,

Just a heads-up: no need for a save button in that section. Actions take effect immediately upon button click.
