### ISSUE TITLE
Remove "show admin bar" option from the plugin

### ISSUE THREAD

**Issue by rahularyan** [anspress/anspress#906]
The functionality of toggling the admin bar's visibility doesn't seem to align with the plugin's purpose. Therefore, it would be more beneficial to remove this feature from the plugin altogether.

**Comment by Kudratullah** [comment]
@rahularyan it will be great.
Meanwhile this addition braking website (header) if user is not logged in, as you can see this code just return true without checking previous status value set by other the original function and any other filter callback.

![image](https://github.com/anspress/anspress/assets/8349994/33ac16e7-fb7a-4fb4-8ed7-9560e31493b6)


https://github.com/anspress/anspress/blob/ef2cd5a3a18dbb6f9fadaae1ce5fb7f2d7eab8c6/includes/hooks.php#L1094-L1100

Please release an update soon as possible removing or fixing the callback.

**Comment by rahularyan** [comment]
Hi @Kudratullah,
I wanted to let you know that the option you were referring to has been removed from AnsPress. Releasing a minor version shortly. Your patience is greatly appreciated.
