### ISSUE TITLE
Still using tinymice editor?

### ISSUE THREAD

**Issue by DoctorGuidance** [anspress/anspress#907]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/anspress/anspress/assets/12963915/b5faa872-1b76-4fa1-b9c7-654ff0b2074d)
Hi again,
with tinymice editor we can't even use our theme font, it is so classically ugly!

how many are the number of development team here? Does anybody cares? or take feedback? Improve anything?

8 years passed and still the same issue here! 

any other Q&A plugin suggested?

**Comment by rahularyan** [comment]
Hi There,
Work is in progress for upcoming version 5.0.0 which will address lots of stuff related to theme and also make plugin compatible with the block editor.
Thanks for your patience.
